# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160923_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
